### ISSUE TITLE
file input form?

### ISSUE THREAD

**Issue by HeyMarcy** [ProNextJS/forms-management#4]
Thanks so much for the great tutorial.
Would it be possible to show an example of an input of type="file"?
My [attempt](https://github.com/HeyMarcy/form-managment-next/blob/main/src/app/FileUpload.tsx) give the following error:
`Type '{ onChange: (...event: any[]) => void; onBlur: Noop; value: File; disabled?: boolean | undefined; name: "file"; ref: RefCallBack; placeholder: string; accept: string; type: "file"; }' is not assignable to type 'InputProps'.
  Types of property 'value' are incompatible.
    Type 'File' is not assignable to type 'string | number | readonly string[] | undefined'.`

**Comment by jherr** [comment]
I am planning to have a file upload and validation section as part of the upcoming course. In the meantime there is an article here that I just published on file uploads: https://www.pronextjs.dev/next-js-file-uploads-server-side-solutions Beyond that there is volunteer support on the Blue Collar Coder Discord server. Please read and follow the #rules before posting.
