### ISSUE TITLE
onSubmit fn in RegistrationForm file doesn't match video

### ISSUE THREAD

**Issue by waldothedeveloper** [ProNextJS/forms-management#5]
Hey @jherr , thank you for the great tutorial about form management. I learned a ton! 
I was reviewing the code attached to the lesson `Implement a Server Action for Handling Form Data` and I noticed that in Github the `onSubmit` on the `<form .../>` is different  to what I see on the video. Maybe a typo? 

What I see on your video: 

<img width="1704" alt="image" src="https://github.com/ProNextJS/forms-management/assets/16472274/cc84f8da-7c5e-4ff9-b6f8-c444062bcab5">

But what I have on Github is: 

![image](https://github.com/ProNextJS/forms-management/assets/16472274/391fda54-1410-424b-81bb-af93268fdd02)

https://github.com/ProNextJS/forms-management/blob/main/src/app/RegistrationForm.tsx#L95C6-L100C11

**Comment by jherr** [comment]
This is intentional. The code in the repo is a corrected version of the code in the video. There was an issue with navigation before form submission that is fixed by this update.

**Comment by waldothedeveloper** [comment]
> This is intentional. The code in the repo is a corrected version of the code in the video. There was an issue with navigation before form submission that is fixed by this update.

Thank you Jack for the quick response! I later on saw the navigation error you mentioned in your response and then understood your answer even better and modified the code.

Building on this great tutorial you put together, I wanted to ask you how do you handle more complex forms where you have for example Files that need to be uploaded - and validated lol - , but you need to show a 'grid' of the 'uploaded' files. 

Look at this Listing Form from Etsy: 

<img width="1033" alt="image" src="https://github.com/ProNextJS/forms-management/assets/16472274/510d8ed7-c9c7-4721-a129-d589f9bc580f">

<img width="1696" alt="image" src="https://github.com/ProNextJS/forms-management/assets/16472274/f8393f00-5473-4155-a481-a63d38b944a7">

The approach I think it could work is

- Using React State to hold an array of selected images from your computer 
- Using this React State to build the grid of images
- Using a hidden input maybe `readOnly` and `value={JSON.stringify([arrayOfPictures])}` that can be used to submit the array of pictures for validation in server side?????
- Can you send a File to a server action using FormData? Or does it need to be converted to some other format? 

With more complex forms like this example is where my vision starts getting blurry. Anyway, I'd love to hear your input on a situation like this, how would you proceed, would you leverage React state combined with hidden inputs to submit the data for validation server side, etc. 

Again, thank you so much for the amazing tutorial!

**Comment by jherr** [comment]
Feel free to jump on the Blue Collar Coder server https://discord.gg/YSnJBu8H and ask your question in the #react forum there. Please read and follow the #rules **CAREFULLY** before posting.
